"""add tables

Revision ID: 160cc8cb219d
Revises: 
Create Date: 2026-04-02 03:20:58.182056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '160cc8cb219d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('universities',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_universities_slug'), 'universities', ['slug'], unique=True)
    op.create_table('faculties',
    sa.Column('university_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['university_id'], ['universities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('university_id', 'slug', name='uq_faculty_university_slug')
    )
    op.create_index(op.f('ix_faculties_university_id'), 'faculties', ['university_id'], unique=False)
    op.create_table('users',
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('avatar_url', sa.String(length=512), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('STUDENT', 'MODERATOR', 'ADMIN', name='userrole'), nullable=False),
    sa.Column('university_id', sa.String(length=36), nullable=False),
    sa.Column('university_changed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['university_id'], ['universities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_university_id'), 'users', ['university_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('actor_id', sa.String(length=36), nullable=True),
    sa.Column('entity', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_id'), 'audit_logs', ['actor_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity'), 'audit_logs', ['entity'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_id'), 'audit_logs', ['entity_id'], unique=False)
    op.create_table('catalog_proposal_logs',
    sa.Column('entity_type', sa.Enum('UNIVERSITY', 'FACULTY', 'SUBJECT', name='proposalentitytype'), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('actor_id', sa.String(length=36), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_catalog_proposal_logs_actor_id'), 'catalog_proposal_logs', ['actor_id'], unique=False)
    op.create_index(op.f('ix_catalog_proposal_logs_entity_id'), 'catalog_proposal_logs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_catalog_proposal_logs_entity_type'), 'catalog_proposal_logs', ['entity_type'], unique=False)
    op.create_table('faculty_proposals',
    sa.Column('university_id', sa.String(length=36), nullable=False),
    sa.Column('proposed_name', sa.String(length=255), nullable=False),
    sa.Column('proposed_slug', sa.String(length=255), nullable=True),
    sa.Column('proposed_description', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='proposalstatus'), nullable=False),
    sa.Column('reviewed_by', sa.String(length=36), nullable=True),
    sa.Column('review_note', sa.Text(), nullable=True),
    sa.Column('approved_faculty_id', sa.String(length=36), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_faculty_id'], ['faculties.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['university_id'], ['universities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_faculty_proposals_created_by'), 'faculty_proposals', ['created_by'], unique=False)
    op.create_index(op.f('ix_faculty_proposals_university_id'), 'faculty_proposals', ['university_id'], unique=False)
    op.create_table('moderator_faculty_scopes',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('faculty_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['faculty_id'], ['faculties.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'faculty_id', name='uq_mod_fac_scope')
    )
    op.create_index(op.f('ix_moderator_faculty_scopes_faculty_id'), 'moderator_faculty_scopes', ['faculty_id'], unique=False)
    op.create_index(op.f('ix_moderator_faculty_scopes_user_id'), 'moderator_faculty_scopes', ['user_id'], unique=False)
    op.create_table('moderator_university_scopes',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('university_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['university_id'], ['universities.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'university_id', name='uq_mod_uni_scope')
    )
    op.create_index(op.f('ix_moderator_university_scopes_university_id'), 'moderator_university_scopes', ['university_id'], unique=False)
    op.create_index(op.f('ix_moderator_university_scopes_user_id'), 'moderator_university_scopes', ['user_id'], unique=False)
    op.create_table('notifications',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('password_reset_tokens',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('token', sa.String(length=128), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_password_reset_tokens_token'), 'password_reset_tokens', ['token'], unique=True)
    op.create_index(op.f('ix_password_reset_tokens_user_id'), 'password_reset_tokens', ['user_id'], unique=False)
    op.create_table('refresh_token_sessions',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('jti', sa.String(length=36), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('replaced_by_jti', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_token_sessions_expires_at'), 'refresh_token_sessions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_refresh_token_sessions_jti'), 'refresh_token_sessions', ['jti'], unique=True)
    op.create_index(op.f('ix_refresh_token_sessions_user_id'), 'refresh_token_sessions', ['user_id'], unique=False)
    op.create_table('subjects',
    sa.Column('faculty_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=True),
    sa.Column('semester', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['faculty_id'], ['faculties.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('faculty_id', 'slug', 'semester', name='uq_subject_faculty_slug_semester')
    )
    op.create_index(op.f('ix_subjects_faculty_id'), 'subjects', ['faculty_id'], unique=False)
    op.create_table('university_proposals',
    sa.Column('proposed_name', sa.String(length=255), nullable=False),
    sa.Column('proposed_slug', sa.String(length=255), nullable=True),
    sa.Column('proposed_description', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='proposalstatus'), nullable=False),
    sa.Column('reviewed_by', sa.String(length=36), nullable=True),
    sa.Column('review_note', sa.Text(), nullable=True),
    sa.Column('approved_university_id', sa.String(length=36), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_university_id'], ['universities.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_university_proposals_created_by'), 'university_proposals', ['created_by'], unique=False)
    op.create_table('user_preferences',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('language', sa.String(length=16), nullable=False),
    sa.Column('email_notifications', sa.Boolean(), nullable=False),
    sa.Column('marketing_notifications', sa.Boolean(), nullable=False),
    sa.Column('theme', sa.String(length=32), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_preferences_user_id'), 'user_preferences', ['user_id'], unique=True)
    op.create_table('materials',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('material_type', sa.Enum('BOOK', 'NOTES', 'SLIDES', 'EXAM', 'ASSIGNMENT', 'LAB', 'CHEATSHEET', 'OTHER', name='materialtype'), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PENDING_REVIEW', 'APPROVED', 'REJECTED', name='materialstatus'), nullable=False),
    sa.Column('subject_id', sa.String(length=36), nullable=False),
    sa.Column('uploaded_by', sa.String(length=36), nullable=False),
    sa.Column('approved_by', sa.String(length=36), nullable=True),
    sa.Column('last_reviewed_by', sa.String(length=36), nullable=True),
    sa.Column('rejected_reason', sa.Enum('WRONG_SUBJECT', 'DUPLICATE', 'UNREADABLE', 'LOW_QUALITY', 'SPAM', 'COPYRIGHT_OR_POLICY_ISSUE', 'OTHER', name='rejectreason'), nullable=True),
    sa.Column('cover_file_id', sa.String(length=36), nullable=True),
    sa.Column('primary_file_id', sa.String(length=36), nullable=True),
    sa.Column('file_count', sa.Integer(), nullable=False),
    sa.Column('total_size', sa.Integer(), nullable=False),
    sa.Column('download_count', sa.Integer(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['cover_file_id'], ['material_files.id'], name='fk_material_cover_file', use_alter=True),
    sa.ForeignKeyConstraint(['last_reviewed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['primary_file_id'], ['material_files.id'], name='fk_material_primary_file', use_alter=True),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_materials_slug'), 'materials', ['slug'], unique=True)
    op.create_index(op.f('ix_materials_status'), 'materials', ['status'], unique=False)
    op.create_index(op.f('ix_materials_subject_id'), 'materials', ['subject_id'], unique=False)
    op.create_index(op.f('ix_materials_uploaded_by'), 'materials', ['uploaded_by'], unique=False)
    op.create_table('moderator_subject_scopes',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('subject_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'subject_id', name='uq_mod_sub_scope')
    )
    op.create_index(op.f('ix_moderator_subject_scopes_subject_id'), 'moderator_subject_scopes', ['subject_id'], unique=False)
    op.create_index(op.f('ix_moderator_subject_scopes_user_id'), 'moderator_subject_scopes', ['user_id'], unique=False)
    op.create_table('subject_proposals',
    sa.Column('faculty_id', sa.String(length=36), nullable=False),
    sa.Column('proposed_name', sa.String(length=255), nullable=False),
    sa.Column('proposed_slug', sa.String(length=255), nullable=True),
    sa.Column('proposed_code', sa.String(length=64), nullable=True),
    sa.Column('proposed_semester', sa.Integer(), nullable=True),
    sa.Column('proposed_description', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='proposalstatus'), nullable=False),
    sa.Column('reviewed_by', sa.String(length=36), nullable=True),
    sa.Column('review_note', sa.Text(), nullable=True),
    sa.Column('approved_subject_id', sa.String(length=36), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_subject_id'], ['subjects.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['faculty_id'], ['faculties.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subject_proposals_created_by'), 'subject_proposals', ['created_by'], unique=False)
    op.create_index(op.f('ix_subject_proposals_faculty_id'), 'subject_proposals', ['faculty_id'], unique=False)
    op.create_table('comments',
    sa.Column('material_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comments_material_id'), 'comments', ['material_id'], unique=False)
    op.create_index(op.f('ix_comments_user_id'), 'comments', ['user_id'], unique=False)
    op.create_table('material_files',
    sa.Column('material_id', sa.String(length=36), nullable=False),
    sa.Column('storage_key', sa.String(length=512), nullable=False),
    sa.Column('preview_storage_key', sa.String(length=512), nullable=True),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=128), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('file_ext', sa.String(length=32), nullable=False),
    sa.Column('file_kind', sa.Enum('IMAGE', 'DOCUMENT', 'ARCHIVE', 'OTHER', name='filekind'), nullable=False),
    sa.Column('file_order', sa.Integer(), nullable=False),
    sa.Column('checksum_hash', sa.String(length=64), nullable=False),
    sa.Column('is_previewable', sa.Boolean(), nullable=False),
    sa.Column('preview_page_count', sa.Integer(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('preview_storage_key'),
    sa.UniqueConstraint('storage_key')
    )
    op.create_index(op.f('ix_material_files_checksum_hash'), 'material_files', ['checksum_hash'], unique=False)
    op.create_index(op.f('ix_material_files_file_kind'), 'material_files', ['file_kind'], unique=False)
    op.create_index(op.f('ix_material_files_material_id'), 'material_files', ['material_id'], unique=False)
    op.create_table('material_ratings',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('material_id', sa.String(length=36), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'material_id', name='uq_material_rating_user_material')
    )
    op.create_index(op.f('ix_material_ratings_material_id'), 'material_ratings', ['material_id'], unique=False)
    op.create_index(op.f('ix_material_ratings_user_id'), 'material_ratings', ['user_id'], unique=False)
    op.create_table('material_reports',
    sa.Column('material_id', sa.String(length=36), nullable=False),
    sa.Column('reporter_id', sa.String(length=36), nullable=False),
    sa.Column('reviewer_id', sa.String(length=36), nullable=True),
    sa.Column('reason', sa.String(length=128), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'RESOLVED', 'DISMISSED', name='reportstatus'), nullable=False),
    sa.Column('resolution_note', sa.Text(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_material_reports_material_id'), 'material_reports', ['material_id'], unique=False)
    op.create_index(op.f('ix_material_reports_reporter_id'), 'material_reports', ['reporter_id'], unique=False)
    op.create_index(op.f('ix_material_reports_reviewer_id'), 'material_reports', ['reviewer_id'], unique=False)
    op.create_table('material_review_logs',
    sa.Column('material_id', sa.String(length=36), nullable=False),
    sa.Column('action', sa.Enum('SUBMITTED', 'APPROVED', 'REJECTED', 'RESUBMITTED', 'MOVED_SUBJECT', 'REQUESTED_REVISION', 'WITHDRAWN', 'REPORTED', 'TAKEDOWN', name='reviewaction'), nullable=False),
    sa.Column('actor_id', sa.String(length=36), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('reason', sa.String(length=128), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_material_review_logs_actor_id'), 'material_review_logs', ['actor_id'], unique=False)
    op.create_index(op.f('ix_material_review_logs_material_id'), 'material_review_logs', ['material_id'], unique=False)
    op.create_table('material_tags',
    sa.Column('material_id', sa.String(length=36), nullable=False),
    sa.Column('tag_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('material_id', 'tag_id')
    )
    op.create_table('saved_materials',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('material_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'material_id', name='uq_saved_material_user_material')
    )
    op.create_index(op.f('ix_saved_materials_material_id'), 'saved_materials', ['material_id'], unique=False)
    op.create_index(op.f('ix_saved_materials_user_id'), 'saved_materials', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_saved_materials_user_id'), table_name='saved_materials')
    op.drop_index(op.f('ix_saved_materials_material_id'), table_name='saved_materials')
    op.drop_table('saved_materials')
    op.drop_table('material_tags')
    op.drop_index(op.f('ix_material_review_logs_material_id'), table_name='material_review_logs')
    op.drop_index(op.f('ix_material_review_logs_actor_id'), table_name='material_review_logs')
    op.drop_table('material_review_logs')
    op.drop_index(op.f('ix_material_reports_reviewer_id'), table_name='material_reports')
    op.drop_index(op.f('ix_material_reports_reporter_id'), table_name='material_reports')
    op.drop_index(op.f('ix_material_reports_material_id'), table_name='material_reports')
    op.drop_table('material_reports')
    op.drop_index(op.f('ix_material_ratings_user_id'), table_name='material_ratings')
    op.drop_index(op.f('ix_material_ratings_material_id'), table_name='material_ratings')
    op.drop_table('material_ratings')
    op.drop_index(op.f('ix_material_files_material_id'), table_name='material_files')
    op.drop_index(op.f('ix_material_files_file_kind'), table_name='material_files')
    op.drop_index(op.f('ix_material_files_checksum_hash'), table_name='material_files')
    op.drop_table('material_files')
    op.drop_index(op.f('ix_comments_user_id'), table_name='comments')
    op.drop_index(op.f('ix_comments_material_id'), table_name='comments')
    op.drop_table('comments')
    op.drop_index(op.f('ix_subject_proposals_faculty_id'), table_name='subject_proposals')
    op.drop_index(op.f('ix_subject_proposals_created_by'), table_name='subject_proposals')
    op.drop_table('subject_proposals')
    op.drop_index(op.f('ix_moderator_subject_scopes_user_id'), table_name='moderator_subject_scopes')
    op.drop_index(op.f('ix_moderator_subject_scopes_subject_id'), table_name='moderator_subject_scopes')
    op.drop_table('moderator_subject_scopes')
    op.drop_index(op.f('ix_materials_uploaded_by'), table_name='materials')
    op.drop_index(op.f('ix_materials_subject_id'), table_name='materials')
    op.drop_index(op.f('ix_materials_status'), table_name='materials')
    op.drop_index(op.f('ix_materials_slug'), table_name='materials')
    op.drop_table('materials')
    op.drop_index(op.f('ix_user_preferences_user_id'), table_name='user_preferences')
    op.drop_table('user_preferences')
    op.drop_index(op.f('ix_university_proposals_created_by'), table_name='university_proposals')
    op.drop_table('university_proposals')
    op.drop_index(op.f('ix_subjects_faculty_id'), table_name='subjects')
    op.drop_table('subjects')
    op.drop_index(op.f('ix_refresh_token_sessions_user_id'), table_name='refresh_token_sessions')
    op.drop_index(op.f('ix_refresh_token_sessions_jti'), table_name='refresh_token_sessions')
    op.drop_index(op.f('ix_refresh_token_sessions_expires_at'), table_name='refresh_token_sessions')
    op.drop_table('refresh_token_sessions')
    op.drop_index(op.f('ix_password_reset_tokens_user_id'), table_name='password_reset_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_token'), table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_moderator_university_scopes_user_id'), table_name='moderator_university_scopes')
    op.drop_index(op.f('ix_moderator_university_scopes_university_id'), table_name='moderator_university_scopes')
    op.drop_table('moderator_university_scopes')
    op.drop_index(op.f('ix_moderator_faculty_scopes_user_id'), table_name='moderator_faculty_scopes')
    op.drop_index(op.f('ix_moderator_faculty_scopes_faculty_id'), table_name='moderator_faculty_scopes')
    op.drop_table('moderator_faculty_scopes')
    op.drop_index(op.f('ix_faculty_proposals_university_id'), table_name='faculty_proposals')
    op.drop_index(op.f('ix_faculty_proposals_created_by'), table_name='faculty_proposals')
    op.drop_table('faculty_proposals')
    op.drop_index(op.f('ix_catalog_proposal_logs_entity_type'), table_name='catalog_proposal_logs')
    op.drop_index(op.f('ix_catalog_proposal_logs_entity_id'), table_name='catalog_proposal_logs')
    op.drop_index(op.f('ix_catalog_proposal_logs_actor_id'), table_name='catalog_proposal_logs')
    op.drop_table('catalog_proposal_logs')
    op.drop_index(op.f('ix_audit_logs_entity_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_university_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_faculties_university_id'), table_name='faculties')
    op.drop_table('faculties')
    op.drop_index(op.f('ix_universities_slug'), table_name='universities')
    op.drop_table('universities')
    op.drop_table('tags')
    # ### end Alembic commands ###
