"""add_material_downloads

Revision ID: f9f52d499cad
Revises: 94604aa85943
Create Date: 2026-05-20 09:42:11.588654

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9f52d499cad'
down_revision: Union[str, Sequence[str], None] = '94604aa85943'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('material_downloads',
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('material_id', sa.String(length=36), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'material_id', name='uq_user_material_download')
    )
    op.create_index(op.f('ix_material_downloads_material_id'), 'material_downloads', ['material_id'], unique=False)
    op.create_index(op.f('ix_material_downloads_user_id'), 'material_downloads', ['user_id'], unique=False)
    op.create_foreign_key('fk_material_primary_file', 'materials', 'material_files', ['primary_file_id'], ['id'], use_alter=True)
    op.create_foreign_key('fk_material_cover_file', 'materials', 'material_files', ['cover_file_id'], ['id'], use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_material_cover_file', 'materials', type_='foreignkey')
    op.drop_constraint('fk_material_primary_file', 'materials', type_='foreignkey')
    op.drop_index(op.f('ix_material_downloads_user_id'), table_name='material_downloads')
    op.drop_index(op.f('ix_material_downloads_material_id'), table_name='material_downloads')
    op.drop_table('material_downloads')
    # ### end Alembic commands ###
